apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sigstore-image-verification
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  rules:
  - match:
      any:
      - resources:
          kinds:
          - Pod
    name: sigstore-image-verification
    verifyImages:
    - imageReferences:
      - "*"
      type: SigstoreBundle
      attestations:
      - type: https://slsa.dev/provenance/v1
        attestors:
        - entries:
          - keyless:
              issuer: https://token.actions.githubusercontent.com
              subject: https://github.com/nirmata/github-signing-demo/.github/workflows/build-attested-image.yaml@refs/heads/main
              rekor:
                  url: https://rekor.sigstore.dev
              additionalExtensions:
                githubWorkflowTrigger: push
                githubWorkflowName: build-attested-image
                githubWorkflowRepository: nirmata/github-signing-demo
        conditions:
        - all:
          - key: "{{ buildDefinition.buildType }}"
            operator: Equals
            value: "https://actions.github.io/buildtypes/workflow/v1"
          - key: "{{ buildDefinition.externalParameters.workflow.repository }}"
            operator: Equals
            value: "https://github.com/nirmata/github-signing-demo"


